import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// Define the interface for the summary data
interface SummaryData {
    overview: string;
    recommendations: string[];
}

export const generatePDF = (data: SummaryData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 25; // Slightly larger margin for a more formal look
    let currentY = margin;

    // --- Header ---
    // Using 'times' font for a professional serif look (closest to Computer Modern available by default)
    doc.setFont("times", "bold");
    doc.setFontSize(24);
    doc.setTextColor(0, 0, 0); // Black for seriousness
    doc.text("BAYMAX AI", pageWidth / 2, currentY, { align: "center" });

    currentY += 8;
    doc.setFontSize(12);
    doc.setFont("times", "italic");
    doc.setTextColor(50, 50, 50); // Dark grey
    doc.text("Professional Medical Consultation Report", pageWidth / 2, currentY, { align: "center" });

    currentY += 15;

    // --- Date and Reference ---
    doc.setFont("times", "normal");
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);

    const date = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });
    const time = new Date().toLocaleTimeString();

    doc.text(`Date: ${date}`, margin, currentY);
    doc.text(`Time: ${time}`, pageWidth - margin, currentY, { align: "right" });

    currentY += 5;
    // Random Reference Number for professional feel
    const refNum = "REF-" + Math.random().toString(36).substr(2, 9).toUpperCase();
    doc.text(`Reference: ${refNum}`, margin, currentY);

    currentY += 10;

    // --- Line Separator ---
    doc.setDrawColor(0, 0, 0);
    doc.setLineWidth(0.5);
    doc.line(margin, currentY, pageWidth - margin, currentY);
    currentY += 15;

    // --- Patient Info (Placeholder) ---
    doc.setFont("times", "bold");
    doc.setFontSize(12);
    doc.text("PATIENT INFORMATION", margin, currentY);
    currentY += 8;

    doc.setFont("times", "normal");
    doc.setFontSize(11);
    doc.text("Name: __________________________", margin, currentY);
    doc.text("ID: __________________________", margin + 80, currentY);
    currentY += 20;

    // --- Consultation Summary ---
    doc.setFont("times", "bold");
    doc.setFontSize(14);
    doc.text("CONSULTATION SUMMARY", margin, currentY);
    currentY += 8;

    doc.setFont("times", "normal");
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);

    // Split text to fit width
    const splitOverview = doc.splitTextToSize(data.overview, pageWidth - 2 * margin);
    doc.text(splitOverview, margin, currentY);
    currentY += splitOverview.length * 6 + 15;

    // --- Recommendations ---
    doc.setFont("times", "bold");
    doc.setFontSize(14);
    doc.text("RECOMMENDATIONS / PRESCRIPTION", margin, currentY);
    currentY += 8;

    // Use autoTable for the list
    const recommendationsData = data.recommendations.map((rec, index) => [index + 1 + ".", rec]);

    autoTable(doc, {
        startY: currentY,
        body: recommendationsData,
        theme: 'plain', // Plain theme for a very serious look
        styles: {
            font: 'times',
            fontSize: 11,
            cellPadding: 3,
            textColor: [0, 0, 0],
        },
        columnStyles: {
            0: { cellWidth: 10, fontStyle: 'bold' },
        },
        margin: { left: margin, right: margin },
    });

    // Get final Y position after table
    // @ts-ignore
    currentY = doc.lastAutoTable.finalY + 30;

    // --- AI Signature ---
    if (currentY + 40 > pageHeight) {
        doc.addPage();
        currentY = margin;
    }

    doc.setFont("times", "italic");
    doc.setFontSize(11);
    doc.text("Electronically signed by:", pageWidth - margin, currentY, { align: "right" });
    currentY += 10;

    doc.setFont("times", "bolditalic");
    doc.setFontSize(14);
    doc.text("Baymax AI System", pageWidth - margin, currentY, { align: "right" });

    currentY += 5;
    doc.setDrawColor(0, 0, 0);
    doc.setLineWidth(0.5);
    doc.line(pageWidth - margin - 60, currentY, pageWidth - margin, currentY);

    // --- Footer ---
    const footerText = "DISCLAIMER: This report is generated by an AI system and is intended for informational purposes only. It does not constitute a medical diagnosis or professional medical advice. Please consult with a certified healthcare provider.";
    doc.setFont("times", "italic");
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);

    const splitFooter = doc.splitTextToSize(footerText, pageWidth - 2 * margin);
    doc.text(splitFooter, pageWidth / 2, pageHeight - 20, { align: "center" });

    // Save the PDF
    doc.save("report.pdf");
};
